functions:
  "fetch_source":
    - command: git.get_project
      params:
        directory: "stitch-android-sdk"

  "install_aws_cli":
    - command: shell.exec
      params:
        script: |
          set -e
          echo "setting up AWS CLI"
          curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
          unzip awscli-bundle.zip
          ./awscli-bundle/install -b ~/bin/aws

tasks:
  - name: run_tests
    commands:
      - func: "fetch_source"
      - command: shell.exec
        params:
          script: |
            echo `$ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-27;google_apis;x86'`
	    echo `echo no | $ANDROID_HOME/tools/bin/avdmanager create avd --force -n test -k 'system-images;android-27;google_apis;x86'`

	    $ANDROID_HOME/tools/emulator -avd test -no-skin -no-audio -no-window &

	    set +e

	    echo "Starting wait command"
	    bootanim=""
	    failcounter=0
	    until [[ "$bootanim" =~ "stopped" ]]; do
   	    	  bootanim=`$ANDROID_HOME/platform-tools/adb -e shell getprop init.svc.bootanim 2>&1`
   		  echo "$bootanim"
   		  if [[ "$bootanim" =~ "not found" ]]; then
      		     let "failcounter += 1"
      		     if [[ $failcounter -gt 15 ]]; then
        	     	echo "Failed to start emulator"
        		exit 1
      		     fi
   	           fi
   		   sleep 1
	    done
	    echo "Done"
	    echo `./gradlew connectedAndroidTest`
  - name: docs_dist
    depends_on:
      - name: run_tests
    commands:
      - func: "fetch_source"
      - func: "install_aws_cli"
      - command: shell.exec
        params:
          silent: true
          script: |
            set -e
            export PATH=$HOME/bin:$PATH
            export AWS_ACCESS_KEY_ID=${sdks_aws_key}
            export AWS_SECRET_ACCESS_KEY=${sdks_aws_secret}
            cd stitch-android-sdk
            echo "building docs"
            ./gradlew generateReleaseJavadoc copyDocsToS3

buildvariants:
- name: linux-64
  display_name: Linux-64
  run_on:
    - baas-linux
  tasks:
    - name: run_tests
    - name: docs_dist
