functions:
  "fetch_source":
    - command: git.get_project
      params:
        directory: "baas-android-sdk"

tasks:
  - name: dist
    commands:
      - func: "fetch_source"
      - command: shell.exec
        params:
          script: |
            set -e
            cd baas-android-sdk
            echo "building SDK"
            # Expect error from sdk.dir
            ./gradlew build

      - command: shell.exec
        params:
          script: |
            set -e
            echo "setting up AWS CLI"
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            ./awscli-bundle/install -b ~/bin/aws
            echo "uploading jars"

      - command: shell.exec
        params:
          silent: true
          script: |
            set -e
            export PATH=$HOME/bin:$PATH
            export AWS_ACCESS_KEY_ID=${sdks_aws_key}
            export AWS_SECRET_ACCESS_KEY=${sdks_aws_secret}
            cd baas-android-sdk
            echo "building SDK"
            ./gradlew copyJarsToS3

buildvariants:
- name: linux-64
  display_name: Linux-64
  run_on:
    - baas-linux
  expansions:
    mongodb_url: http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.4.1.tgz
  tasks:
    - name: dist
