functions:
  "fetch_source":
    - command: git.get_project
      params:
        directory: "stitch-android-sdk"

  "install_aws_cli":
    - command: shell.exec
      params:
        script: |
          set -e
          echo "setting up AWS CLI"
          curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
          unzip awscli-bundle.zip
          ./awscli-bundle/install -b ~/bin/aws

tasks:
  - name: run_tests
    commands:
      - func: "fetch_source"

      - command: shell.exec
        params:
          silent: true
          script: |
            set -e

            cd stitch-android-sdk
            echo "building test apk"
            ./gradlew assembleAndroidTest < /dev/null

            APK_FILE_PATH="./stitch/build/outputs/apk/androidTest/debug/stitch-debug-androidTest.apk"
            TEST_PACKAGE="com.mongodb.stitch.android.test"
            URL="${device_farm_url}?test_type=android&test_package=$TEST_PACKAGE"

            echo "running test apk"
            RESULT=`cat $APK_FILE_PATH | curl $URL -H "Authorization: ${device_farm_secret}" --data-binary @-`
            echo $RESULT | grep -P "OK \(\d+ tests\)"

  - name: docs_dist
    depends_on:
      - name: run_tests
    commands:
      - func: "fetch_source"
      - func: "install_aws_cli"
      - command: shell.exec
        params:
          silent: true
          script: |
            set -e
            export PATH=$HOME/bin:$PATH
            export AWS_ACCESS_KEY_ID=${sdks_aws_key}
            export AWS_SECRET_ACCESS_KEY=${sdks_aws_secret}
            cd stitch-android-sdk
            echo "building docs"
            ./gradlew generateReleaseJavadoc < /dev/null
            ./gradlew stitch:copyDocsToS3

buildvariants:
- name: linux-64
  display_name: Linux-64
  run_on:
    - baas-linux
  tasks:
    - name: run_tests
    - name: docs_dist
