functions:
  "fetch_source":
    - command: git.get_project
      params:
        directory: "stitch-java-sdk"

  "setup_mongod":
    - command: shell.exec
      params:
        shell: "bash"
        script: |
          set -e
          curl --silent ${mongodb_url} | tar xvz
    - command: shell.exec
      params:
        shell: "bash"
        background: true
        script: |
          set -e
          cd mongodb-*
          echo "starting mongod..."
          mkdir db_files
          ./bin/mongod --dbpath ./db_files --port 26000
    - command: shell.exec
      params:
        shell: "bash"
        script: |
          set -e
          cd mongodb-*
          echo "waiting for mongod to start up"
          ./bin/mongo --nodb --eval 'assert.soon(function(x){try{var d = new Mongo("localhost:26000"); return true}catch(e){return false}}, "timed out connecting")'
          echo "mongod is up."

  "setup_stitch":
    - command: shell.exec
      params:
        shell: "bash"
        silent: true
        script: |
          set -e
          echo export AWS_ACCESS_KEY_ID=${test_aws_key} >> creds
          echo export AWS_SECRET_ACCESS_KEY=${test_aws_secret} >> creds
    - command: shell.exec
      params:
        shell: "bash"
        script: |
          set -e
          echo "cloning stitch"
          mkdir -p src/github.com/10gen
          git clone git@github.com:10gen/stitch src/github.com/10gen/stitch

          echo "downloading libmongo"
          wget --quiet "https://s3.amazonaws.com/stitch-artifacts/stitch-mongo-libs/stitch_mongo_libs_linux_64_patch_1f02b06ec6fd48bad0b725b77bc194c84f839f53_5ab7216fc9ec44724e08f194_18_03_25_04_11_28/libmongo.so"
          chmod +x libmongo.so

          echo "building transpiler"
          cd src/github.com/10gen/stitch/etc/transpiler
          yarn install && yarn run build -t ${transpiler_target}
    - command: shell.exec
      params:
        shell: "bash"
        background: true
        script: |
          set -e
          export GOPATH=`pwd`
          export PATH="`pwd`:$PATH"
          export STITCH_PATH=$GOPATH/src/github.com/10gen/stitch
          export PATH="$PATH:$STITCH_PATH/etc/transpiler/bin"
          echo "running stitch"
          # TODO: Probably better to get an API key added to mimic cloud
          go run $STITCH_PATH/cmd/auth/user.go addUser -domainID 000000000000000000000000 -mongoURI mongodb://localhost:26000 -salt 'DQOWene1723baqD!_@#' -id "unique_user@domain.com" -password "password"
          go run $STITCH_PATH/cmd/server/main.go --configFile $STITCH_PATH/etc/configs/test_config.json
    - command: shell.exec
      params:
        shell: "bash"
        script: |
          counter=0
          until $(curl --output /dev/null --silent --head --fail http://localhost:9090); do
            echo "checking for API server to be up..."
            sleep 1
            let counter++
            if [ $counter -gt 100 ]; then
              exit 1
            fi
          done

  "setup_emulator":
    - command: shell.exec
      params:
        shell: "bash"
        background: true
        script: |
          set -e
          EMULATOR_PID=''
          cleanup() {
              kill $EMULATOR_PID
              wait $EMULATOR_PID
              avdmanager delete avd -n android_avd
          }

          trap cleanup EXIT

          # Create the AVD
          echo no | avdmanager create avd --force -k "system-images;android-26;google_apis;x86_64" --name android_avd -p android_avd

          # Start the AVD in the background
          emulator @android_avd -no-window -no-audio &
          EMULATOR_PID=$!
          sleep infinity
    - command: shell.exec
      params:
        shell: "bash"
        script: |
          set -e
          echo "Waiting for emulator to be ready"

          # Wait for ADB to detect the device
          adb wait-for-device

          # Wait until boot animation stops (this can take a long time!)
          bootanim=""
          failcounter=0
          timeout_in_sec=600
          until [[ "$bootanim" =~ "stopped" ]]; do
            bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &`
            if [[ "$bootanim" =~ "device not found" || "$bootanim" =~ "device offline"
              || "$bootanim" =~ "running" ]]; then
              let "failcounter += 1"
              echo "Waiting for emulator to start"
              if [[ $failcounter -gt timeout_in_sec ]]; then
                echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
                exit 1
              fi
            fi
            sleep 1
          done

          echo "Emulator is ready"

  "setup_embedded":
    - command: shell.exec
      params:
        shell: "bash"
        script: |
          # TODO: Remove this script when embedded is published
          set -e
          git clone https://github.com/mongodb/mongo-java-driver.git
          cd mongo-java-driver
          git checkout embedded
          ./gradlew install

tasks:
  - name: lint
    commands:
      - func: "fetch_source"
      - func: "setup_embedded"
      - command: shell.exec
        params: 
          shell: "bash"
          script: |
            set -e
            cd stitch-java-sdk
            ./gradlew checkstyle findbugs pmd lint --continue --warning-mode=all < /dev/null

  - name: run_core_tests
    commands:
      - func: "fetch_source"
      - func: "setup_mongod"
      - func: "setup_stitch"
      - func: "setup_embedded"
      - command: shell.exec
        params: 
          shell: "bash"
          script: |
            set -e
            cd stitch-java-sdk

            echo "running java tests"
            echo "test.stitch.baseURL=http://localhost:9090" > local.properties
            ./gradlew test --info --continue --warning-mode=all < /dev/null

  - name: run_android_tests
    commands:
      - func: "fetch_source"
      - func: "setup_mongod"
      - func: "setup_stitch"
      - func: "setup_emulator"
      - func: "setup_embedded"
      - command: shell.exec
        params: 
          shell: "bash"
          script: |
            set -e
            cd stitch-java-sdk

            echo "running android tests"
            echo "test.stitch.baseURL=http://10.0.2.2:9090" > local.properties
            ./gradlew connectedAndroidTest --info --continue --warning-mode=all < /dev/null

post:
  - command: attach.xunit_results
    params:
      files:
        - "./stitch-java-sdk/core/build/test-results/test/*.xml"
        - "./stitch-java-sdk/core/admin-client/build/test-results/test/*.xml"
        - "./stitch-java-sdk/server/build/test-results/test/*.xml"
        - "./stitch-java-sdk/examples/todo/build/test-results/test/*.xml"
        - "./stitch-java-sdk/android/core/build/outputs/androidTest-results/connected/*.xml"
        - "./stitch-java-sdk/android/mongodb-local/build/outputs/androidTest-results/connected/*.xml"
        - "./stitch-java-sdk/android/mongodb-stitch/build/outputs/androidTest-results/connected/*.xml"

  - command: s3.put
      params:
        aws_key: ${mciuploads_aws_key}
        aws_secret: ${mciuploads_aws_secret}
        local_files_include_filter:
          - stitch-java-sdk/**/build/outputs/findbugs/*.xml
        remote_file: mms/${build_id}/${task_name}/findbugs-
        bucket: mciuploads
        permissions: public-read
        content_type: text/xml

buildvariants:
- name: linux-64
  display_name: Linux-64
  run_on:
    - baas-linux
  expansions:
    mongodb_url: http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.4.4.tgz
    transpiler_target: node8-linux
  tasks:
    - name: lint
    - name: run_core_tests
- name: linux-64-android
  display_name: Linux-64-Android
  run_on:
    - baas-java-sdk
  expansions:
    mongodb_url: http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.4.4.tgz
    transpiler_target: node8-linux
  tasks:
    - name: run_android_tests
